apps:
  Home Assistant: io.homeassistant.companion.android
  YouTube: com.google.android.youtube
  Spotify: com.spotify.music

# Optional: limit the dropdown options shown in HA
# If omitted or empty, all keys from 'apps' will be shown.
visible:
  - Home Assistant
  - YouTube
  - Spotify
